apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura-deployment
  labels:
    app: conversao-temperatura-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura-web
  template:
    metadata:
      labels:
        app: conversao-temperatura-web
    spec:
      containers:
        - name: conversao-temperatura-web
          image: eduosumi/conversao-temperatura:v1
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-web
spec:
  selector:
    app: conversao-temperatura-web
  ports:
    - port: 8080
      nodePort: 30000
  type: NodePort